#-------------------------------
# Site Settings
title: Nilufer Akalin
description:


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: 'HOME'
      url: '/'
    - title: 'ABOUT'
      url: '/about'
    - title: 'Research'
      url: '/research'
    - title: 'Teaching'
      url: '/teaching'
    - title: 'Publications'
      url: '/publications'
    - title: 'Media and coverage'
      url: '/media-and-coverage'
    - title: 'Contact'
      url: '/contact'

    


#-------------------------------
# Google Analytics
google-analytics:  # Add your GA Tracking Id
